FROM jenkins/jenkins:lts

USER root

# Install basic tools
RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean

# Install Docker CLI (simple way)
RUN curl -fsSL https://get.docker.com | sh

# Install kubectl
RUN curl -LO "https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    rm kubectl

USER jenkins